name: NEXT Deploy
on:
  push:
    branches: main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code.
        uses: actions/checkout@main
        with:
          ref: main

      - name: Install Dependencies
        run: |
          yarn install

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: AKIA5CEN4IFD55OG22KW
          aws-secret-access-key: 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
          aws-region: ap-northeast-2

      - name: Deploy Next.js app
        run: |
          yarn deploy